// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy31gJyTI7efFPPBCP674WW6QlHz5gAC4',
    appId: '1:1062370297936:web:4f37327017784793132955',
    messagingSenderId: '1062370297936',
    projectId: 'employeemanagementapp-7d7ed',
    authDomain: 'employeemanagementapp-7d7ed.firebaseapp.com',
    storageBucket: 'employeemanagementapp-7d7ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVvo0BvHYekurxvQPY7TRaLiI8qqARr_U',
    appId: '1:1062370297936:android:fb83bea1c1f5ba2a132955',
    messagingSenderId: '1062370297936',
    projectId: 'employeemanagementapp-7d7ed',
    storageBucket: 'employeemanagementapp-7d7ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKu-Q2a7mLh1nKWcGlx56-7JO9Q8B3Upk',
    appId: '1:1062370297936:ios:0df1602d44be87ee132955',
    messagingSenderId: '1062370297936',
    projectId: 'employeemanagementapp-7d7ed',
    storageBucket: 'employeemanagementapp-7d7ed.firebasestorage.app',
    iosClientId: '1062370297936-vgoipha4bro80kmth92r9femkl7b4n54.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeemanagement.employeeManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKu-Q2a7mLh1nKWcGlx56-7JO9Q8B3Upk',
    appId: '1:1062370297936:ios:0df1602d44be87ee132955',
    messagingSenderId: '1062370297936',
    projectId: 'employeemanagementapp-7d7ed',
    storageBucket: 'employeemanagementapp-7d7ed.firebasestorage.app',
    iosClientId: '1062370297936-vgoipha4bro80kmth92r9femkl7b4n54.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeemanagement.employeeManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy31gJyTI7efFPPBCP674WW6QlHz5gAC4',
    appId: '1:1062370297936:web:36e5b9ac757e554e132955',
    messagingSenderId: '1062370297936',
    projectId: 'employeemanagementapp-7d7ed',
    authDomain: 'employeemanagementapp-7d7ed.firebaseapp.com',
    storageBucket: 'employeemanagementapp-7d7ed.firebasestorage.app',
  );
}
